# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Jobs are the step by step instruction to your runner/vm what to do
jobs:

# Name of this job
  build:

    # Which OS should this run on
    runs-on: ubuntu-latest
    
    # Actual instructions you give to the machine to execute
    steps:
    # download your source code - equivalent to your git clone command
    - uses: actions/checkout@v3
    
    # download .NET SDK to your runner
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
      # equivalent to doing dotnet restore in your commandline
      # dotnet restore will download all your dependencies and make sure your 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
